### ISSUE TITLE
Use multi-line input for creating and editing snippets

### ISSUE THREAD

**Issue by bdunn313** [adammpkins/SnipSnap#6]
Currently, it's not straightforward to add a multi-line snippets. We should allow for that.

**Comment by adammpkins** [comment]
I updated to use a textarea for multiline. Go ahead and review and we'll close this.

**Comment by adammpkins** [comment]
Textarea is there, but saving (and seemingly even re-running the script) will truncate the multiline back to one line.

**Comment by adammpkins** [comment]
Implement multiline code snippet preservation

- Use base64 encoding to save and load code snippets
- Change field separator to '|||' for improved reliability
- Update View function to properly display multiline code
- Preserve newlines and special characters in snippets

Commit 21ff29e
